### ISSUE TITLE
DrumGizmo kit import

### ISSUE THREAD

**Issue by jeffbeale** [sadko4u/lsp-plugins#145]
Since DrumGizmo kits are also an XML file with a second midimap XML, is it possible to import them into the Multisampler series?

**Comment by sadko4u** [comment]
I've explored drumgizmo kits. There is a nuance related to the drumkit: each sample is a result of multitrack record. There is possibility to identify the main channel for each instrument but LSP Multisampler allows now to load only first or first and second channels of the audio sample. Before DrumGizmo samples can be imported, LSP Multisamper requires additional channel selection for each file to be added.

**Comment by unsaph3** [comment]
Understood. Thanks for exploring that and getting back to me about it, and
keep up the good work.

**Comment by a13** [comment]
I think SFZ format is much more popular

**Comment by JamesPeters667** [comment]
DrumGizmo might be more advanced than some people realize, at least for use with drum samples. (It's clearly not much of a sampler in other regards, but for drums it is actually pretty good.) I think it's a bit outside the intended range of the LSP Sampler plugins at least for what it can specifically do for drums.

There are a number of capabilities of DrumGizmo kits which would need to be matched (not including new features being developed):

-The ability to use multichannel WAV files (as already mentioned), or groups of mono/stereo WAV files combined*
-Up to 127 possible samples for each velocity level
-Round-robin capability (to an arbitrary number of round robins; I'm not sure if there's a limit or not)
-Directed choke functionality (not just choke groups, but specificity of which samples should choke which other ones, not necessarily mutually exclusive)

The kits that I've made for DrumGizmo for instance require all of these features. They could be "scaled down", but that means figuring out what elements of the kit to discard to simplify it for importing into an LSP Sampler plugin (which I don't think would be easy to do automatically, since it will vary based on the specifics of the kit being imported).

Then there are some features about DrumGizmo which aren't part of the kit files, but are beneficial to have in the plugin:

-Velocity humanization (which acts like a "velocity compressor", so that a number of drum hits on a single note repetitively reduce in velocity after the initial attack period, as a real drummer would tend to do during a drum roll)
-Velocity curve adjustment
-Disk streaming

Unless the LSP Sampler plugins are planned to evolve into something which can handle all these features, it's probably not worth pursuing the ability to import DrumGizmo kits.

*Multi-channel WAV files aren't required for DrumGizmo. For each "sample" within the instrument XML files, separate one-channel or two-channel WAV files can be combined (such that you can have one mono proximity mic WAV file, a stereo overhead WAV file, and a stereo room WAV file, all acting as "one sample" as the instrument file classifies a "sample"). Then the instrument XML defines how the samples are assigned to varying velocity levels, and how many round robins there are (if you assign multiple samples to the same velocity level).

**Comment by jeffbeale** [comment]
All good points James, which is why I should have closed this on Oct 1st, 2020 when I last commented on this issue. Marking as closed.
