### ISSUE TITLE
Option for the .cfg file to use relative file paths

### ISSUE THREAD

**Issue by chrisanthropic** [sadko4u/lsp-plugins#159]
An option for the .cfg file to use relative file paths would be helpful.

It would allow us to store a hydrogen kit right beside the lsp-sampler .cfg file and move both without breaking the config filepath, which also opens up the ability to more easily share kits/configs with others.

Thanks for the great plugins!

**Comment by sadko4u** [comment]
I believe I'll add this feature in the 1.2.0 release, not earlier.

**Comment by chrisanthropic** [comment]
That's great, thanks for considering it!

**Comment by sadko4u** [comment]
I had some time and implemented this feature.
Will be available in 1.1.28 release.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 706bff5454c3ff7bf5d40804e6401ee419e6426d

**Comment by chrisanthropic** [comment]
This is awesome, thanks so much!

Related, I recented wrote some documenation around importing and configuring a hydrogen kit into lsp-sampler, as well as how to route a fanout drum subgroup in Ardour.

Not sure if you have a spot for docs or are interested, but I wanted to say thanks and let you know these are available:
- https://github.com/chrisanthropic/LinuxMusicProduction/wiki/Import-a-hydrogen-drumkit-into-lsp-sampler
- https://github.com/chrisanthropic/LinuxMusicProduction/wiki/Create-a-fanout-drum-subgroup-for-your-lsp-sampler-hydrogen-drumkit

**Comment by sadko4u** [comment]
I also want to thank you for supporting the project with donations.

Nice to see a documentation from your side. Is it your personal documentation or targeted to some community?

I think it would be nice to have some more detailed documentation about user experience and some tips (e. g. how to import Hydrogen drumkits here):
https://lsp-plug.in/?page=manuals&section=multisampler_x12

Since the documentation is public, you may submit a pull request with changes to this file:
https://github.com/sadko4u/lsp-plugins/blob/master/src/doc/manuals/plugins/multisampler.php

**Comment by chrisanthropic** [comment]
This is just a personal wiki I recently started to create some cheatsheets for myself, I'll open a PR to the docs.

**Comment by sadko4u** [comment]
Available in 1.1.28 release!
