### ISSUE TITLE
LV2 plugins don't "remember" their size after being resized in REAPER

### ISSUE THREAD

**Issue by frescoalfredo** [sadko4u/lsp-plugins#180]
Reaper now has LV2 support in its development builds. I've been testing LSP LV2 plugins in it.

The plugins resize, but when the plugin window is closed and re-opened, they return to the default size.

I tried this with the rack mount view in both states, just in case it made a difference. (It doesn't.)

I also tried the following: resize the plugin, save a preset, make that preset the new default preset. This didn't work either (but it does work with other LV2 plugins which can resize).

For comparison, here's source code of an LV2 plugin which can resize, and does remember its size after closing and re-opening the plugin window (including closing the Reaper project and re-opening it):

It's x42's "auto tune":
https://github.com/x42/fat1.lv2

x42 has a few free plugins which can resize, but this one also has a GUI piano that scales when the plugin resizes, so it's probably the best example I can find of an LV2 plugin which can resize (one which has source code available to view, anyway).

I'm using Manjaro XFCE 20.2.1. Someone else reported this as well (on the Reaper forum) and he's using Debian testing/Gnome 3.

**Comment by sadko4u** [comment]
Hello.

1. The 'resize' feature doesn't specify the way the size of plugin is stored.
2. The 'resize' feature works not well sometimes: if you specify the size of plugin in Ardour, it can not be set to less value.
3. I already performed the request to LV2 community to implement more adequate ui:Resize function to be able to specify minimum and maximum possible sizes of the UI (and also reporting recommended size to host would be useful, too) but AFAIR @drobilla has concluded that ui:Resize has bad design and needs to be reworked. Maybe I'm wrong but @drobilla should better explain all about ui:Resize feature.

**Comment by drobilla** [comment]
Yes, that feature is questionable at best, and possibly just entirely garbage that needs to be removed, but I'm not entirely sure about that last part.  Many plugins, and LSP in particular, abuse it, causing all kinds of issues.  In general window sizes should be managed by the window system APIs, and ui_resize should be considered a last resort kludge.  My hope is to deprecate it and remove support entirely because it causes way more problems than it solves, but we need more plugins and hosts doing things properly first.

In any case, it seems questionable to me for plugin UIs to be responsible for remembering window sizes.  The host creates the windows and can do more or less whatever it likes with them, according to how it wants its UI to work.  Including embedding them and not having a top level repositionable or resizable window at all...

**Comment by sadko4u** [comment]
For me, the main problem is that if I try to report the size of plugin window to Ardour usin UI:resize, It won't allow to the user to make the size of window less than reported even if it is allowed to the plugin's window.
By the other side, if I set the horizontal and vertical sizes of plugin window to specific values, the host may become unsatisfied with these values and send another X event to resize my window. Then my toolkit becomes unsatisfied by the size of window and emits yet another one resize event and host and tookit finally fall into infinite resize-loop.

**Comment by sadko4u** [comment]
So, @drobilla what's the proper behavior of LV2 UI should be?
Set the minimum and maximum possible sizes of window using WM_NORMAL_HINTS?
Resize the window with XResizeEvent?
For me it's not too hard to change the protocol. The main question is how the host will handle it.

**Comment by drobilla** [comment]
In an ideal world, yeah, just setting the window properties/hints.

But just doing that probably won't work in existing hosts right now, because everybody has been working around everyone else's bugs.  It's going to take someone going across the whole stack and making things work properly without leaning on ui_resize() to sort out this mess.

I'm still not entirely sure about plugin-initiated resizes, though, we might still need the API for that if the host can't catch the Configure event or equivalent, but hopefully not, and it shouldn't be used in the normal case to just set things up anyway.

**Comment by sadko4u** [comment]
@drobilla and what about the way I've previously suggested? The plugin can report minimum, maximum and desired size for the window (horizontal and vertical) and the host handles it?

For example, if the desired size differs to the current size of the plugin window, the host initiates the resize of the plugin's window to the desired, and the size notification comes back to the plugin and it can safely handle it without resize loop.

Since we have not only X11 protocol but also Wayland is coming and there is also Windows subsystem which works different with user windows (don't know how things are going with MacOS, sorry), wouldn't it be the compromise?

**Comment by drobilla** [comment]
> Set the minimum and maximum possible sizes of window using WM_NORMAL_HINTS?

This.

**Comment by falkTX** [comment]
FYI latest carla git (or upcoming 2.3.1) can automatically size its LV2 window (the host parent one given to plugins to render into).
No need for any extensions, everything happens with pure X11.
Carla will detect that the child window has changed and will automatically adapt its host window to match.

So that can be used for testing.

on a related note, I already modified DPF so its develop branch will also not make use of LV2 UI resize features/extensions.
will adapt JUCE / DISTRHO-Ports at some point too.
