### ISSUE TITLE
lsp-plugins-jack not working in Linux Mint 20.2

### ISSUE THREAD

**Issue by osilverstone** [sadko4u/lsp-plugins#206]
After installing all the LSP Plugins packages I have found that the standalone JACK plugins do not appear in the application menu and do not have any executable files in /usr/bin or /usr/local/bin. I have had these plugins working on my computer previously but now they do not work.

**Comment by sadko4u** [comment]
How did you install the plugins?
Have you tried the official binaries?

**Comment by osilverstone** [comment]
First I installed all the packages from the repositories then uninstalled and built them from the source code; in each case there are no menu icons. I have also tried installing from the repositories from a Linux Mint live disk and have the same issue there.

**Comment by sadko4u** [comment]
In the latest release the icon installation process has been moved to a dedicated target for `make`:
```
make install_xdg
```
This target you should perform manually since I got many claims related to GNOME environment which doesn't follow the XDG standard and displays all LSP icons in the main menu without grouping them into a common folder.

Hope that helps.

**Comment by osilverstone** [comment]
That's done it, thank you

**Comment by sadko4u** [comment]
Nice to see the problem has been solved.
