### ISSUE TITLE
Clarification on Compressors documentation

### ISSUE THREAD

**Issue by Digitalone1** [sadko4u/lsp-plugins#208]
Hello everyone, I updated the EasyEffects documentation which uses the Stereo Sidechain Compressor and Multiband Compressor.

It's interesting that general compressors use Attack, Release and Threshold parameters while LSP ones have Attack Time/Threshold and Release Time/Threshold. So what is referred as Threshold in general guides is the Attack Threshold in LSP, but I didn't fully understand what the Release Threshold is doing.

LSP manual says "`relative to the Attack Thresh threshold that sets up the threshold of Release Time`", but it's not very intuitive and I still don't understand. I even tried to change its value but I don't hear any significant difference.

About Attack and Release Times, there are so much definitions on the Internet, but I followed the ones in this [guide](https://www.attackmagazine.com/features/columns/gregory-scott-demolishing-the-myths-of-compression/) which I think is the best. Attack Time is the `length of time it takes a compressor to apply roughly two-thirds of the targeted amount of gain reduction` while Release Time is the `time it takes a compressor to restore two-thirds of the reduced gain to the compressed signal`.

Those definitions are not considering the Threshold, but I assume the application/restoration of gain reduction is made around the Threshold, which is the Attack Threshold in LSP. So which is the role of the Release Threshold in all of this?

Another parameter to clarify is the Sidechain Reactivity. The manual says "`reactivity of the sidechain signal`" which is not a real explanation of what it is doing.

I hope an intuitive explanation is provided. Anyway, thanks for the great work and the big quality of your audio plugins!

**Comment by sadko4u** [comment]
Hello!
The behaviour is the following.
If you don't use the 'Release' threshold, it is set by default to -Inf gain. So compressor works as a usual device with Attack/Release/Threshold set.
If you set the 'Release' threshold (which is not absolute and is set as relative to the 'Attack' value), then if your current envelope value is above the 'Release' threshold, the compressor uses 'Release' value for the release time, otherwise it switches to the 'Attack' value used for release time. It is a good way to define a cut point where the long release time becomes reset to short one (or vice verse).

**Comment by Digitalone1** [comment]
@sadko4u so if I understood the correct behavior, considering the following parameters:

- Downward Mode
- Attack Threshold: -10 dB
- Release Threshold: -60 dB

Envelope above `-10 + (-60) = -70 db`: the Release Time is used for the gain restoration.
Envelope below - 70 db: the Attack Time is used for the gain restoration.

Am I correct?

Can you please also explain the Sidechain Reactivity?

**Comment by sadko4u** [comment]
@Digitalone1 yes, exactly.

The control signal of the compressor's sidechain can be split into three instances:
- raw signal - the signal that is passed to the sidechain input or the input of compressor (when no external sidechain is used)
- the sidechain signal - the signal processed by the sidechain module:
  - peak doesn't do any processing except of performing the abs() function on the signal;
  - LPF processes the signal with the single-pole low-pass filter like in RC contour;
  - Uniform processes the signal with the uniform digital filter which averages the absolute amplitudes between some count of previously received samples;
  - RMS - works in the same manner as the uniform but computes root-mean-square instead of absolute average.
- The envelope of the compressor which is computed from sidechain signal with attack and release values applied.

The sidechain reactivity defines the number of samples averaged by the RMS and Uniform filters (the more samples are processed, the more smooth the result is) and the computed time constant for the LPF mode which is part of the exp(k * t) expression which describes the transient response of such filter.
So, the less reactivity is, the less sidechain module affects the input signal, the more reactivity is, the more smooth signal comes out of the sidechain module.

Additionally, sidechain module is common for all plugins that perfomr dynamic processing of signal.

**Comment by Digitalone1** [comment]
Thank you @sadko4u
