### ISSUE TITLE
Feature request. Loudness 384 khz

### ISSUE THREAD

**Issue by TheBestKmanEver** [sadko4u/lsp-plugins#228]
wondering if you can add support to the Loudness plugin of 384 khz, my soundcard has 32bit 384khz, im just wanting to get the least amount of latency i can possibly get, 194 khz gives me 40ms delay in easyeffectts (yea yea this is puny but that's not the point :P), i tried running at 384khz and my audio plays but the Loudness plugin will not work
im not wanting 384khz because "better quality" which is complete BS, im wanting it for the fact that the higher sample rate i go, the less latency i get

**Comment by sadko4u** [comment]
Hmm. How does the sample rate affect the latency?
I mean, you can just lower the size of audio buffer to achieve the least possible latency.
I don't understand the application of such extreme settings. Could you please explain your setup more detailed?

**Comment by TheBestKmanEver** [comment]
the below screenshots show that there is more latency the lower the sample rate becomes, sadly the Loudness wont work beyond 192khz and i want to be overkill because IT MUST BE PERFECT!!! :P    if you refuse to do this then i dont mind but i would be thankful if you did :P

![Screenshot at 2022-03-19 18-06-14](https://user-images.githubusercontent.com/35676228/159140119-07398861-96ac-4e0b-90fc-9c038f41ef5e.png)
![Screenshot at 2022-03-19 18-04-32](https://user-images.githubusercontent.com/35676228/159140120-6534db64-e6f7-42b2-9a25-19476046fd95.png)
![Screenshot at 2022-03-19 18-01-02](https://user-images.githubusercontent.com/35676228/159140121-8e6d2279-5a97-41b0-980e-658de9610443.png)

**Comment by sadko4u** [comment]
Hello again!

Oh, now I see and understand your case. You're trying to compensate the latency of the Loudness Compensator tool.
And you're using pretty large FFT frame size.
The frequency resolution of FFT also depends on the sample rate. If you raise the sample rate, the frequency resolution of FFT lowers proportionally and you need to make the FFT window larger.
So instead of this you can just reduce the FFT size to 4096 samples and make the sample rate 4 times lower. And you'll get almost the same result.
Additionally, you'll significantly reduce the CPU load for your system.
According to my experience, even 1024-2048 FFT frame size works well.
Anyway, I'll try to reduce the latency but not earlier than 1.2.0 release.

**Comment by TheBestKmanEver** [comment]
ok thanks, i use the max FFT cause i like it to be as good as i can get it because i like to be overkill :P

**Comment by TheBestKmanEver** [comment]
also cpu load isnt an issue for me, yes it does add some load but not enough for me to worry about

**Comment by sadko4u** [comment]
Increased the maximum supported sample rate up to 384 kHz.
Will be available in 1.2.4 release.
https://github.com/lsp-plugins/lsp-plugin-fw/commit/cb0c83f60655f379b8b7b526e8ba6d6d57430492

**Comment by sadko4u** [comment]
Available in 1.2.4!
