### ISSUE TITLE
LV2 Samplers not saving settings with projects

### ISSUE THREAD

**Issue by thoth-amon** [sadko4u/lsp-plugins#233]
Steps to reproduce:

1: Load LV2 version LSP Sampler (doesn't matter which, mono, multi-sampler etc) in Carla.
2: Add sample.
3: Move dials about 
4: Save carla project.
5: Restart carla and open project.

All the dials are reset to default. This is not a problem for the vst versions. I also got this result in MusE DAW.

**Comment by sadko4u** [comment]
Can confirm the problem for other hosts, too.
Looking up for the solution.

**Comment by sadko4u** [comment]
Fixed the regression in the `lsp-plug-fw` plugin framework.
The problem was that several controls were considered being legacy LV2 controls and not saved in a LV2:State data structure.
The corresponding patch: https://github.com/lsp-plugins/lsp-plugin-fw/commit/6c9f2cfa5c4c4ac1e1e1394396cf2fd5f0dcda67
WIll be available in 1.2.1.

**Comment by sadko4u** [comment]
Available in 1.2.1.
