### ISSUE TITLE
Weird makefile framework instead of submodules?

### ISSUE THREAD

**Issue by IcedQuinn** [sadko4u/lsp-plugins#240]
Is there a particular reason that there is a makefile step that performs a bunch of fixed checkouts of github repos? This is exactly what git submodules do.

**Comment by sadko4u** [comment]
The `lsp-plugins` repository refers other projects that can be considered as standalone projects and that can be built as libraries. These projects have their own dependencies, too.
In this case, the build system thinks on the submodules not in term of **piece of code** but in term of **source code as provided package with dependencies**.
Since packages have dependencies from one to another, organizing them into the standard tree of submodules will cause the circular recursion problem when checking out submodules with the `--recursive` option.
Instead of this, we can just check out all the dependencies into a plain directory and link them together. So that's how the build system works.

**Comment by IcedQuinn** [comment]
So it has to do with the pseudo monorepo problem (ex. an independent repository importing things, but the pseudo-monorepo parent wants to collect the dependencies together in a flat heirarchy instead of a tree.)

**Comment by sadko4u** [comment]
Yes, the behaviour is more likely modern Java build tools do: they obtain packages from the artifactory and then build the derived project using the artifacts. But for C++, we don't have pre-compiled artifacts and have to deal with source code instead.

**Comment by IcedQuinn** [comment]
A little weird and tedious to audit as an outsider, but since i don't have to deal with that with the release tarballs I don't have to justify it to the package managers.
