### ISSUE TITLE
Support default configs for Hydrogen kits & make path to kits in configs variable

### ISSUE THREAD

**Issue by chrisanthropic** [sadko4u/lsp-plugins#242]
Hi again,

I have a feature request specifically around the Hydrogen Kit UI/UX and config and I've tried to be as clear as possible - hopefully this makes sense - it's a more specific version of what I was trying to ask for [here](https://github.com/sadko4u/lsp-plugins/issues/159) and is similar to the request [here](https://github.com/sadko4u/lsp-plugins/issues/197)

### Desired workflow 1
- set a default `kit config` directory
- when loading a hydrogen drumkit, check the default `kit config` directory and if there is a `.cfg` file matching the name of the `.xml` drumkit file, then load that config by default.

### Desired workflow 2
- allow users to set a custom `kit config` directory
- when loading a hydrogen drumkit, check the custom `kit config` directory and if there is a `.cfg` file matching the name of the `.xml` drumkit file, then load that config by default.

### set a default 'kits' & 'kits config' path
- current default kits path is set [here](https://github.com/sadko4u/lsp-plugins/commit/6e8d2cbba44a71f5d31a14f02a25d8955ad743dd#diff-a7f0875ad5724e34ef0b19fc20417dc0ac16765de12dc0f3054d0caf52c7f4f3R33-R36)
  - would need to be updated to allow users to override the current hardcoded defaults
- use this new setting when writing paths in the code: `$KIT_PATH`
- follow the same pattern to create a custom default hydrogen `kits config` directory
- EX: if a kit has a `.cfg` right beside it and is named identically, load it by default
  - `$KIT_PATH/synthie-1/drumkit.xml`
  - `$KIT_PATH/synthie-1/drumkit.cfg`

### (optionally) set a default 'kit config' path
- any kit loaded will search this directory for a `.cfg` file with the same name and if one is found it will be loaded by default.
- EX: if a kit has an identically named `.cfg` found in the `$KIT_CONFIG` path, load it by default
  - `$KIT_PATH/synthie-1/drumkit.xml`
  - `$KIT_CONFIG/synthie-1/drumkit.cfg`

### use relative paths in sample path so we can share configs
- when exporting a `.cfg` file, use a `$KIT_PATH`  variable when writing paths
  - ex: `$KIT_PATH/Synthie-1` where `$KIT_PATH` is the default config path that can be overridden by users.
  - ex: `$KIT_PATH/Synthie-1` is shareable vs my highly custom `/mnt/audio/projects/sound_library/hydrogen/kits/Synthie-1` which is not.

**Comment by sadko4u** [comment]
### The documentation to the upcoming feature

Additional feature Override Hydrogen kits is also provided and can be enabled via the `User paths...` menu item or the `UI behavior` → `Override Hydrogen kits` menu item.

The main idea of the feature is following.

Additionally to the usual Hydrogen drumkit installation paths, user can specify additional drumkit installation path in the `User paths` dialog. This will trigger automatic rescan of Hydrogen drumkits on each change of this parameter. All found drumkits will be available in the `Import` → `Installed Hydrogen drumkits` menu.

User also can specify the `Hydrogen drumkit override path` that will be used to search for configuration files that will override the original Hydrogen drumkits.

If the `Override Hydrogen kits` option is set, the behaviour of the plugin is the following.

When loading hydrogen drumkit via the `Import` → `Hydrogen drumkit file...` menu item or selecting one of the drumkits listed in the `Import` → `Installed Hydrogen drumkits` menu, the plugin removes the base path of the selected file if it matches one of the following paths:

* Typical hydrogen drumkit system installation paths (only when importing from the list of installed drumkits):
  * `/usr/share/hydrogen`
  * `/usr/local/share/hydrogen`
  * `/opt/hydrogen`
  * `/share/hydrogen`
* Typical hydrogen drumkit user paths in user's home directory (only when importing from the list of installed drumkits):
  * `.hydrogen`
  * `.h2`
  * `.config/hydrogen`
  * `.config/h2`
* The `User Hydrogen kits path` if it is specified.
* The `Override user Hydrogen kits path` if it is specified.

If the base path has been successfully removed, the plugin tries to search the file with the same relative path but the different extension (`*.cfg`) in the following directories:

* The `Override user Hydrogen kits` path if it is specified.
* The `User Hydrogen kits` path if it is specified.

If the corresponding configuration file was found, the plugin uses this file for loading drumkit settings instead of the original Hydrogen drumkit file.

Also note that `User Hydrogen kits path` and `Override user Hydrogen kits path` allow to use system environment variables for path substitutions. For example, the following value:

```
/path/to/kit/${KIT_NAME}
```

Will be interpreted as:

```
/path/to/kit/my_drumkit
```

If the system environment variable `KIT_NAME` is set to `my_drumkit`.

**Comment by sadko4u** [comment]
Available in 1.2.5 release!
