### ISSUE TITLE
Plugins not possible to use in non-standard location?

### ISSUE THREAD

**Issue by tonebender** [sadko4u/lsp-plugins#26]
Tested the LinuxVST edition of lsp-plugins in Reaper for Linux.
When adding them to a "non standard" VST directory, such as ~/Multimedia/VST (in my case), the plugins don't show up in Reaper. It seems that putting the core plugin in a standard location such as /usr/lib/vst solves this. But it would be reasonable if the core plugin could reside in any plugins directory chosen in Reaper's plugin preferences.

**Comment by sadko4u** [comment]
The main reason is because plugin libraries are just wrappers for the core library. You have non-standard location of plugins, so the plugin library just can not find the core library.
In linux, there's no standard API to detect the location of library it was loaded from. It seems that I additionally need to add parsing of /proc/self/maps to detect the actual location of the library.

**Comment by sadko4u** [comment]
Checked on my system. Placed VST binaries to ~/Media/VST path and scanned by Ardour. Plugins have been successfully found.
Merged all changes into **devel** branch, commit c3debb4a78a70a695434efd60cc9043dbbbbf27b
Fix will be published with the 1.1.6 release.

**Comment by falkTX** [comment]
Why not use `dladdr` for this?
You can know the absolute path of a library on POSIX.

See http://man7.org/linux/man-pages/man3/dladdr.3.html

I use it in carla (as plugin) to find the installed prefix.

**Comment by sadko4u** [comment]
Good point, l'll definitely add this function to wrappers.
