### ISSUE TITLE
Knob is not getting updated

### ISSUE THREAD

**Issue by oldcastlehq** [sadko4u/lsp-plugins#289]
The knob from sampler series from v1.2.4 is not getting updated when you use it.

![2022-12-22_21-36](https://user-images.githubusercontent.com/20318144/209222056-24277717-2b65-4d48-859f-0c15cbd147bb.png)

![02](https://user-images.githubusercontent.com/20318144/209223242-9ddd2f96-ae1c-4b2e-bff4-59b4fe501a1d.png)

![03](https://user-images.githubusercontent.com/20318144/209223262-c7837d8b-b629-4f36-8d3e-f6d2af905efa.png)

Not sure if it's relevant, but I used a laptop with the touchpad.

**Comment by sadko4u** [comment]
Hello!
The main problem here is that the knob has a large limit of around 60 seconds.
That's why you see the `Tail Cut` knob as not updated.
But actually it is.
We're thinking on limiting all of the knobs with the maximum duration of the sample.
But at this moments knobs allow to set up the maximum possible value provided by the plugin and, that's why, are so stiff.

**Comment by sadko4u** [comment]
Updated behaviour in 1.2.5
