### ISSUE TITLE
EQ - Low Shelf filter not working correctly

### ISSUE THREAD

**Issue by Utini2000** [sadko4u/lsp-plugins#29]
Good evening,

I am using PulseEffects which is using lsp-plugins to handle the equalizier. 
One thing I noticed is that the low shelf filter is behaving weird in that it seems to have a way higher gain than I actually set it to.  

For example, I have a EQ profile that an acoustic laboratory made for me with their software. 
It includes a low shelf filter with a certain frequency, q-factor and gain. Those settings work fine under e.g. Windows. How ever, with lsp-plugins / pulseeffects it doesn't. 
The EQ Profile is shown as .pdf here (14 bands in total):
https://www.dropbox.com/s/k7wry3s24r2y8sc/Sennheiser%20HD800S%20%2318002%20pt1.pdf?dl=0
https://www.dropbox.com/s/way36c2dofncrvc/Sennheiser%20HD800S%20%2318002%20pt2.pdf?dl=0

There is already a ticket on the github of pulseeffects:
https://github.com/wwmm/pulseeffects/issues/421

Any ideas?

**Comment by sadko4u** [comment]
Hello. The design of filters for LSP is different to pulse ones, and, of course, different to Apo/Peacer or any another EQ that you use. Do you have the issue with only Low-shelf filter?

**Comment by Utini2000** [comment]
Hey there,  
so far I can only hear the issue with the low-shelf filter. 
The other filters I use are Peak (Bell), maybe there is an issue too but I didn't notice or can't hear it without a direct comparison? 
Is there a conversation I could do to get my settings work with LSP?

**Comment by sadko4u** [comment]
I actually don't know because I don't know the characteristics of filters for whic you've created the profile. Yes, I can agree that some filters have some errors in implementation that currently are their specific features but even if I did straightforward implementation, I can not guarantee that they will match Apo/Peacer filters.
I think @CrocoDuckoDucks can help discovering the problem.

**Comment by sadko4u** [comment]
I've found implementation of APO filters:
https://sourceforge.net/p/equalizerapo/code/HEAD/tree/trunk/filters/BiQuad.cpp

Too trivial for LSP because for each filter only one biquad section is used.
We can simply implement all these APO filters as additional filter types for LSP.

**Comment by Utini2000** [comment]
Hmm I don't really understand this. I thought there is only one correct way to process a filter?
But it seems like there are different methods, the one being used by APO seems to be the most common?

**Comment by sadko4u** [comment]
>I thought there is only one correct way to process a filter?
Nope, there's not. If you run LSP Parametric Equalizer and play with extreme filter settings like Q, Slope, type and transform function, you'll see that they povide much more features rather APO ones. But because they provide more features, they actually have completely another design. 
What we can do in LSP is just copying the code that computes APO's biquad filters and implementing them as separate 'special' filters for the parametric eq. Filters will match APOs ones only if all five coefficients (a1, a2, b0, b1, b2) of computed biquad filter will match.

> But it seems like there are different methods, the one being used by APO seems to be the most common?
As I said before, APO has another algorithm for computing it's filters. The good news is that this algorithm is open (see link below), so we can re-implement it in LSP plugin kit. The bad news is that currently I'm very busy with another features and can not say the date when this feature will be deployed.
Maybe @CrocoDuckoDucks will help with it.

**Comment by CrocoDuckoDucks** [comment]
Hey there!
I will take a look at this and revert in the next few days.

**Comment by Utini2000** [comment]
@CrocoDuckoDucks that would be awesome! I talked to /u/oratory1990 and he also thinks that the easiest solution would be to implement the APO filter.

**Comment by CrocoDuckoDucks** [comment]
@Utini2000 , as an update, I will take care of implementing the APO filters, which by the way appear to be a standard textbook implementation. I will revert back when something is ready to be tested by you. Stay tuned.

**Comment by Utini2000** [comment]
Awesome, thank you a lot!

**Comment by Utini2000** [comment]
@CrocoDuckoDucks Hey there, any news? :)

**Comment by sadko4u** [comment]
Be patient, please. I already observe commits in **github-issue-29** branch. @CrocoDuckoDucks had made some changes, it seems already to be working but needs a bit to be polished.

**Comment by sadko4u** [comment]
Computing code of APO filters has been successfully ported to the tree. The only things left are: matching behaviour of several UI controls to APO's ones, writing documentation and releasing the new build.

**Comment by Utini2000** [comment]
Awesome! Sorry, I didn't mean to rush or hurry. 
Next time I will try to follow and figure out the commits on a github branch :)

**Comment by sadko4u** [comment]
Today finally we've got APO filters ported to the LSP Plugins bundle. All changes have been merged into **devel** branch with this commit: 34a764cc2be49e08b4ad2e6b239a16064e87927a

**Comment by sadko4u** [comment]
All changes are available in the 1.1.7 release that was just published.

**Comment by wwmm** [comment]
Thank you for this work @sadko4u  and @CrocoDuckoDucks! As soon as the new version hits the Arch Linux repo I will expose these new filters in PulseEffects.

It seems to me that the year of the news in https://lsp-plug.in/?page=news is wrong

**Comment by sadko4u** [comment]
>It seems to me that the year of the news in https://lsp-plug.in/?page=news is wrong
The year has been fixed, thanks.
