### ISSUE TITLE
Memory leak from GUI

### ISSUE THREAD

**Issue by AaronAyub** [sadko4u/lsp-plugins#311]
LSP doesn't seem to release memory after the GUI is closed in any plugin host, such as Carla or REAPER.

Upon opening the GUI for any LSP plugin, the memory usage increases according to top, or REAPER's performance meter. When closing the GUI window, the memory usage does not decrease at all, unlike other graphical plugins. Repeatedly opening and closing the GUI steadily increases the memory usage until REAPER or Carla crashes.

The version of lsp-plugins is 1.2.5. This problem occurs with both CLAP and LV2 plugin formats.

**Comment by sadko4u** [comment]
Hello! The problem seems to be related to the [cairo](https://www.cairographics.org/) font cache. Even if the font is not used, it is kept in the memory by cairo for future. Every start of the UI loads the new copy of the custom font to the memory and it is kept by cairo. The solution can be achieved by migrating from cairo custom font rendering to [freetype](http://freetype.org/) custom font rendering. But this is not trivial task and requires some time for solution.

**Comment by sadko4u** [comment]
Fixed memory leakage issued by the libcairo font cache on the plugin UI close. Moved custom font rendering solution to direct usage of libfreetype.

**Comment by sadko4u** [comment]
Fixed in 1.2.7
