### ISSUE TITLE
speakers blown up

### ISSUE THREAD

**Issue by sjomae** [sadko4u/lsp-plugins#334]
Using the stereo compressor in non-mixer. The max value is 1000 (output gain). Are you sure that's right?

**Comment by sadko4u** [comment]
You should consider that LSP Plugins use the 'raw' gain value instead of decibels under the hood. That means, that gain='1000' actually means `20*log10(1000) = +60 dB'. For zero gain output, you should use '1' instead.
This is not a bug, this is how LSP deals with logarithmic values for different audio plugin formats.

**Comment by sjomae** [comment]
It boosts the signal with +60 dB max? That will break every speaker (and ears if you're unlucky) isn't it?

**Comment by sadko4u** [comment]
The output volume is 0 dB by default. Just don't set the output volume to +60 dB.

**Comment by sjomae** [comment]
Are other similar plugins having the same approach? Cause I just made a human mistake (with a not 100% correct working gui interface in non-mixer, one wrong click of a mouse or mistyping a dot is enough). It's obviously a very dangerous plugin to use then. Equipment is just a big blow, but ears are harder to recover.

**Comment by sadko4u** [comment]
All of the plugins allow to set up output level above 0 dB because sometimes you need to adjust a volume compensation.
