### ISSUE TITLE
CLAP plugins have invalid default parameter values

### ISSUE THREAD

**Issue by messmerd** [sadko4u/lsp-plugins#346]
Many of the CLAP plugins have invalid default parameter values.
That is, `clap_param_info`'s `default_value` falls outside the `min_value` to `max_value` range.

One example is A/B Tester 2x Stereo, which has a parameter named "Reset channel rating".
For this parameter, `min_value` = 1.0 and `max_value` = 10.0, but `default_value` = 0.444444.

I discovered this while writing my own CLAP host, and confirmed this with [clap-validator](https://github.com/free-audio/clap-validator).
I'm using the latest release (v1.2.11) of the LSP plugins.

**Comment by sadko4u** [comment]
I think the reason is because I implement [normalization functions](https://github.com/lsp-plugins/lsp-plugin-fw/blob/master/include/lsp-plug.in/plug-fw/wrap/clap/helpers.h#L322-L453) to [implement logarithmic parameters](https://github.com/free-audio/clap/issues/285) but forgot to explicitly set `min_value` to `0` and `max_value` to `1`.

**Comment by sadko4u** [comment]
Introduced several fixes for issues found by `clap-validator`.

https://github.com/lsp-plugins/lsp-plugin-fw/commit/2cb21418eee02582c0609525746caaaa004baf00

Added ticket on the `clap-validator` github page:

https://github.com/free-audio/clap-validator/issues/14

**Comment by sadko4u** [comment]
Fixed in 1.2.12.
