### ISSUE TITLE
Loading IR freezes Reaper (1.1.7)

### ISSUE THREAD

**Issue by Sangeppato** [sadko4u/lsp-plugins#36]
I'm using Reaper and everything was fine until the 1.1.7 release. With the latest update if I try to load an IR using the IR Loader the whole DAW just freezes and I'm forced to kill it.

**Comment by sadko4u** [comment]
Thanks for report. Seems to be reproducible for both VST and standalone versions of plugins.

**Comment by sadko4u** [comment]
That's a silly regression. These commits of the **github-issue-36** branch should fix the problem: 5d55187ad710f59c7d2e8dcbca5b2f7b0824b206
f8d2c174ed5ae68a87576f287007d96f0990431f

Anyway, the bug is important because many non-LV2 plugins are affected (LV2 standard provides it's own offline job scheduler as an extension). So I'm forced to do a new release within few days.

**Comment by sadko4u** [comment]
If you can build plugins from source, please confirm that there are no problems more.

**Comment by Sangeppato** [comment]
Wow you were super quick!
Yes, I've built the plugins from the **github-issue-36** branch and I can confirm that they now work just like they used to, thank you very much!

**Comment by sadko4u** [comment]
Changes have been merge into **devel** branch: 5497e8971c1a2a758882ce5ecb9b9b6b6fd7055b

**Comment by sadko4u** [comment]
Release 1.1.9 has been issued.
