### ISSUE TITLE
inline display queue redraw called even if there is nothing to redraw

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#46]
Currently LSP-Plugins call for inline display to be redrawn, even if there is nothing happening with sound or the UI.
This makes them quite heavy, as it needs to redraw stuff all the time when there is no need for it.

**Comment by sadko4u** [comment]
It's hard to make the controllable redraw: actually I need to save the actual state of plugin on each redraw, then compare states in each DSP cycle to check whether plugin needs redraw or not. For compressors and equalizers it is possible but not for plugins with dynamically changing graphs like analyzer, trigger, etc. By other side, plugins schedule updates at the fixed frame rate. By default, it's 20 frames per second but can be overrided by the lv2ui:updateRate value.

**Comment by falkTX** [comment]
I see.
Still, there are some things that can be done as you say. The eqs that does not show a graph can check if parameters have changed during run, and only trigger redraw if so.
For the analyzers, perhaps checking if audio is muted? perhaps you already do this

I dont follow your last comment though.
lv2ui:updateRate is a UI property, it is not valid within the context of the DSP/plugin side.
(Carla already throttles the inline display to 30fps btw)

**Comment by sadko4u** [comment]
I've made a short code review.
Equalizers are already quering draw only when settings are changed:
https://github.com/sadko4u/lsp-plugins/blob/04cc45a4aee3bd3a46ecbd0a9160d0d87f8f8a32/src/plugins/para_equalizer.cpp#L615
https://github.com/sadko4u/lsp-plugins/blob/04cc45a4aee3bd3a46ecbd0a9160d0d87f8f8a32/src/plugins/para_equalizer.cpp#L673
Here, we request redraw only when the final equalization curve has been changed:
https://github.com/sadko4u/lsp-plugins/blob/04cc45a4aee3bd3a46ecbd0a9160d0d87f8f8a32/src/plugins/para_equalizer.cpp#L965

Also, plugins do not issue query_draw() when they are deactivated because query_draw is called only from process() callback.

About other plugins: some of them have a reactivity in their state change. So even if there is no data at input, internal state will be updated. Also, for most of plugins their 'bypass' button works as a hot bypass. So actually you always can turn off/enable plugin without clicks/pops on the output.

If you have noticed, JACK version of plugins also implement their own inline display feature.
![image](https://user-images.githubusercontent.com/12834464/55060724-23055280-5083-11e9-8007-356c441cf397.png)
![image](https://user-images.githubusercontent.com/12834464/55060741-331d3200-5083-11e9-9d5a-58b4e27129d5.png)

But I was required to reduce the frame rate to 5 FPS because the transfer of icon data between the UI and XOrg was extremely heavy for XOrg and window manager.
So I believe the bottleneck can be also somewhere else. Are you available to profile the inline display rendering thread?

I've created the **github-issue-46** and backported some build flags from other branch, so you can rebuild LSP Plugins with '-pg' flags by issuing the command:
```
make clean
make profile
```

**Comment by falkTX** [comment]
I know carla is a bottleneck too. the gui stuff is python and needs to call a C function, get its data and then convert back. This part can for sure be optimized a lot.
But I saw that a few plugins are requesting redraw every single time without the need for it.
Drumgizmo seems to be on the same situation.

In any case, I will investigate this more deeply at a later time, right now I have no time for this.

**Comment by falkTX** [comment]
btw, thanks for the investigation on your side.
Maybe I jumped the gun when reporting this ticket, though I think not. Will let you know when I have more details.

**Comment by sadko4u** [comment]
You can do a simple and effective optimization by just not drawing inline displays for plugins that are out of the patchbay view (if you haven't done it yet). If you work with DSP as a standalone process, there will be additional performance penalty for the IPC.
Controlling the redraw of inline display in most cases is a non-trivial task, so sometimes is much more effective to just redraw the inline display one more times or drop some frames if they are rendered periodically.

**Comment by falkTX** [comment]
> You can do a simple and effective optimization by just not drawing inline displays for plugins that are out of the patchbay view (if you haven't done it yet).

This is already handled by Qt itself, only the stuff that appears on screen gets redrawn.
There is an initial full draw for the mini-canvas/preview thing, but then it should work as you say.

**Comment by sadko4u** [comment]
@falkTX I think I'll close this issue since there is no need to perform any fixes currently.
If you meet some problems with inline display, you're welcome to file a new issue.
