### ISSUE TITLE
lsp-plugins incompatible to jack1 (due to jack_midi_reset_buffer)

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#5]
As noted in [my other issue](#4 ), I'm about to move lsp-plugins to the [community] repository on Arch Linux. During packaging another thing stroke me as fairly odd: lsp-plugins can only be compiled using jack2! This is something that should be circumvented at all costs, as (in theory) jack1 and jack2 are in feature parity.
The problem seems to be the use of `jack_midi_reset_buffer`, which afaik [will be removed in a future release of jack2](https://github.com/jackaudio/jack2/issues/382)! It's not safe to rely on it.

Here's my build output, when building with jack1:
[lsp-plugins-jack1.txt](https://github.com/sadko4u/lsp-plugins/files/2437451/lsp-plugins-jack1.txt)

**Comment by sadko4u** [comment]
I think I should analyze the output of
`pkg-config --modversion jack`
then.
As far as I remember, in Jack 1 there is no **jack_midi_reset_buffer** at all and, also, there is no **jack_midi_clear_buffer** present in headers, too. Maybe I'm wrong because never used Jack 1 and in my distro only Jack2 is comint out-of-the-box.
I'll try to reproduce it on Raspbian because there are both available.

**Comment by sadko4u** [comment]
Seems to be fixed in commit 3dcd7506b7272941c304c5311f13deab23c078a4
I've reproduced on all my systems, it builds everywhere, also on Raspbian with jack1 installed.

**Comment by sadko4u** [comment]
Please confirm the fix

**Comment by dvzrv** [comment]
I've created a combined patch from the arch-build branch vs. 1.1.4. This fixes the compatibility issue! :)
