### ISSUE TITLE
LSP limiter (LV2) does not report latency, even though has port marked as reportsLatency

### ISSUE THREAD

**Issue by alex-tee** [sadko4u/lsp-plugins#55]
LSP limiter and possibly other plugins report 0 latency in LV2. it must report the correct latency when you pass it 0 samples as the LV2 spec says:

> As a special case, when sample_count is 0, the plugin should update any output ports that represent a single instant in time (e.g. control ports, but not audio ports). This is particularly useful for latent plugins, which should update their latency output port so hosts can pre-roll plugins to compute latency. Plugins MUST NOT crash when sample_count is 0.

http://lv2plug.in/doc/html/group__lv2core.html#a3cb9de627507db42e338384ab945660e

i also tried with more than 0 samples but it still reports 0 latency. it has a lookahead control so it should report the appropriate latency

**Comment by sadko4u** [comment]
Thank you for a report. I'll explore it at the middle-end of the next week because I'm currently having a vacation and being hard to manage the code repository.

**Comment by sadko4u** [comment]
Had found some time to look at the code. Seems to be a real bug related to limiter plugin.

**Comment by sadko4u** [comment]
Created **github-issue-55** branch.
This commit should fix the problem: c99cf11fa027ee5027be9aa0e0cd30afc3c681f7
@alex-tee, are you available to test and confirm the fix?

**Comment by alex-tee** [comment]
@sadko4u it reports the correct latency now, but not when first initialized. since its default lookahead is 5ms it should also report that latency when the plugin is run right after it's initialized.

**Comment by sadko4u** [comment]
It seems to be impossible (or am I missing something?) because:
1. At first run(), the wrapper runs update_settings() to compute state of plugin and it's latency.
https://github.com/sadko4u/lsp-plugins/blob/7dee6da832f3b306340bf38cc01432a6fa22f2a9/include/container/lv2/wrapper.h#L1357-L1362
2. After that, in the same method the process() method is executed that forces the plugin to report latency.
https://github.com/sadko4u/lsp-plugins/blob/7dee6da832f3b306340bf38cc01432a6fa22f2a9/include/container/lv2/wrapper.h#L1364-L1365
3. LV2 wrapper Always reports latency if the latency port is connected.
https://github.com/sadko4u/lsp-plugins/blob/7dee6da832f3b306340bf38cc01432a6fa22f2a9/include/container/lv2/wrapper.h#L1379-L1388

Checked in Ardour at the session load:
1. First run() was issued with default values, so the reported latency was 240 samples.
2. Ardour changed lookahead to 20 ms as was saved in the session.
3. Second run() reported latency of 960 samples.

So I see only two cases:
1. Input ports are connected to plugin before run() but are not initialized with their default values at the first run().
2. At the first run(), the latency output port is not connected to plugin, so it can not report the latency.

Moreover, the citate from the official manual does not say anything about how the plugin should react on the input ports' values when calling run(0). I believe it is implementation-specific until @drobilla will clarify the proper behaviour.

Anyway, it would be interesting to build this commit: 7dee6da832f3b306340bf38cc01432a6fa22f2a9
with following set of instructions:
```
make clean && make trace && make install
```
And grab then the output of ```stderr``` as plugin's main log.

**Comment by sadko4u** [comment]
Maybe @x42 also can give some suggestions about the relation between run() method, input ports' state and the latency value report.

**Comment by sadko4u** [comment]
> The zero length case is just a bit strange because it doesn't make sense to write any audio at all in that case, but it can make sense for control/event ports.

@drobilla, do I right understand that in other words it will sound like "plugins should report latency according to the current state of input ports when run() is executed even when sample_count value is zero"?

**Comment by drobilla** [comment]
Yes, as the above quote from the docs says.

**Comment by sadko4u** [comment]
> Yes, as the above quote from the docs says.

@drobilla, thank you. The only question is, is it possible to re-formulate the documentation because for me as a non-native speaker was hard to understand it from the first time?

@alex-tee, now your turn. Is it possible to run plugins with trace log enabled and capture the output?

**Comment by drobilla** [comment]
Sure, but it's not obvious to me what's unclear.  To my eyes, it explicitly says twice that control outputs need to be updated (once in general and once about latency).  Would you find it more clear if the second sentence included the fact that this is about sample_count of zero?  I assumed that was implied by the context.

**Comment by sadko4u** [comment]
@drobilla, I think that the sentence that says that latency **should be always** reported respectively to the actual state of input control ports when the run() method is called, not depending on number of passed samples. The 'e.g.' in text sounds for me as 'for example', so it sounds a bit confusing and relaxing strict rule of taking in attention the values of input ports.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: e63dced1bd987dbd013df3098d3fa6a45a3826f0

**Comment by sadko4u** [comment]
Removed branch **github-issue-55**.

**Comment by sadko4u** [comment]
Available in the 1.1.11 release!
