### ISSUE TITLE
cannot run tests

### ISSUE THREAD

**Issue by magnetophon** [sadko4u/lsp-plugins#8]
As part of the packaging for NixOS, I [was asked](https://github.com/NixOS/nixpkgs/pull/47694#discussion_r222534306) to run the tests.

When I build the pkg, and then run
```
./.build/src/jack/lsp-plugins-test-plugin utest
```
I get:
```
[ERR] Could not find LSP JACK core library
```

Also: I don't see a corresponding binary for the LV2 and VST plugins.

This is using the 1.1.4 release, since a package should use a release, if available.

**Comment by sadko4u** [comment]
This is not a unit test.
Unit tests are called in such manner:
```
.build/lsp-plugins-test utest
```
You're trying to execute test plugin which normally should be hidden in distribution but currently is enabled because compilation flag `-DLSP_NO_EXPERIMENTAL` is not defined during build.

Also, for building unit tests, you should cleanup project tree and do a special build:
```
make clean
make test
```
Then executable `lsp-plugins-test` will be available in `.build` directory.

All corresponding information is also here:
https://github.com/sadko4u/lsp-plugins/issues/4

**Comment by magnetophon** [comment]
Yes, that solves it, thanks!  :)
