### ISSUE TITLE
Documenting API/ABI breakages

### ISSUE THREAD

**Issue by mikhailnov** [sadko4u/lsp-plugins#86]
Hello,

Just a small hint and/or wish from the perspective of a package maintainer.
Changelog of pulseeffects 4.7.2 https://github.com/wwmm/pulseeffects/blob/master/CHANGELOG.md#472 tells that lsp-plugins changed API. But it is not documented in release notes.
Unfortunately, most Linux distros do not have automatical ABI trackage as for example ALT Linux does, so, to a package maintainer, it is critical to be aware of API and ABI breakages to rebuild and/or patch packages linked with/using lsp-plugins (and here I think dlopen() is used, so even ABI tracking will not help to detect breakages).
I did not check information from PulseEffects's changelog, please correct me if I misunderstood something.
Thank you!

**Comment by sadko4u** [comment]
Hello!
It was documented:
```
* Bypass button now supports LV2:enabled designation, that makes plugin to work more smooth with the host.
```
But not so detailed as it could be.

The main problem is that LV2 standard provides lv2:enabled designation:
https://lv2plug.in/ns/lv2core/lv2core.html#enabled

But does not provide lv2:disabled or lv2:bypass designation (@drobilla, @x42, any thoughts?).

So 'bypass' button behaved as negation of 'enabled' button, so it could be contra-intuitive for that users who use automation of this button in DAW.

As a workaround, you may detect whether plugin has 'bypass' control or not. Otherwise just set the opposite value to the 'enabled' parameter.

Sad but this 'breakage' is a more strict following to the LV2 standard.

**Comment by drobilla** [comment]
Breaking the API of plugins (for example changing the symbol of an existing port) is not allowed in LV2: https://lv2plug.in/ns/lv2core#minorVersion

That kind of change means the plugin needs to have a new URI.

**Comment by sadko4u** [comment]
@drobilla 
You didn't understand my question properly. I asked you about why LV2 standard does only provide lv2:enabled feature and does not provide lv2:disabled or lv2:bypass designation? Since LV2 is a very complicated standard and there's not always possible to immediately follow it's strict rules, such features could help to keep the original URI of plugin.

**Comment by drobilla** [comment]
@sadko4u The value of the enabled parameter covers all those things (as the documentation describes).  It would be hugely more confusing and complicated for everyone if there were three different designations that all did the same thing, except with different values standing for different cases.  Everyone would have to implement all three everywhere (except almost certainly wouldn't), that would be a nightmare.

There are better ways to deal with compatibility breakage which could be developed (like pointing at mostly-compatible replacement plugins), and would be more generally useful.  The spec, in general, can't add every possible version of everything that happens to be implemented in some plugin somewhere.

**Comment by sadko4u** [comment]
@drobilla Your position is clear.

Anyway, even if LSP Plugins followed the requirement of [minorVersion](https://lv2plug.in/ns/lv2core#minorVersion), the integration with **pulseeffects** still would broken since all URIDs of plugins should be changed.

From two evils - changing URId - and renaming one single port I prefer renaming of the port since it can be easier handled and worked around by the host.

So, I officially announce that LSP Plugins won't follow the requirement of [minorVersion](https://lv2plug.in/ns/lv2core#minorVersion) until serious significant changes of the plugin will be made.

> There are better ways to deal with compatibility breakage which could be developed (like pointing at mostly-compatible replacement plugins), and would be more generally useful. 

This is wrong. Especially when you distribute plugins as a bundle, you won't keep older version of plugins in bundle since it is unreasonably expensive. If we consider that some software can't handle the removal of parameter and addition of another one parameter (which is, actually, the result of parameter renaming) in TTL files, then TTL files are completely unusable.

> The spec, in general, can't add every possible version of everything that happens to be implemented in some plugin somewhere.

That's lie. When you've developed LV2 standard, I believe you've looked at another audio plugin standards. And as example, in VST there is no **enabled** port/feature/designation. But there's an **effSetBypass** function which controls soft bypass feature. So you could consider that someone will call a bypass button as **bypass** (disabled by default), which is more natural, rather than **enable** (enabled by default) and keep some ways for keeping compatibility of plugins with another standards.

I believe that the complexity (and confusing developers/users) we will become only because LV2 documentation is a complete mess of alphabetically-sorted URIDs without definition of their co-relations of one to another. If **lv2:enabled** and **lv2:bypass** were described nearby one to another and one referenced another, there won't be any confusions ever.

**Comment by sadko4u** [comment]
@drobilla 
An addition to previous post:

![image](https://user-images.githubusercontent.com/12834464/77333527-9bedc780-6d34-11ea-9360-135010fe5406.png)

How now all set of plugins released before 2018-09-18 should deal with **lv2:enabled** property if it goes in counterpart with their current **bypass** understanding? They should increment their 'major' versions and change URIDs? Don't you think that you've taken too much?

Moreover, definition of **lv2:enabled** goes into counterpart with **lv2:minimum**, **lv2:maximum** and **pp:hasStrictBounds** properties:
```
If this value is greater than zero, the plugin processes normally. If this value is zero, the plugin is expected to bypass all signals unmodified. The plugin must provide a click-free transition between the enabled and disabled (bypassed) states.
```

**Comment by drobilla** [comment]
You are of course free to break your plugins if you want.

> How now all set of plugins released before 2016-09-18 should deal with lv2:enabled property if it goes in counterpart with their current bypass understanding?

Well, think about it for a second.  How could you do this?  How about making the bypass port do nothing, hiding it in UIs, and adding the enabled port?  This would mostly work except for old sessions that have automation for it, but you've broken that regardless.

> Don't you think that you've taken too much?

The rules are there to prevent breaking user's sessions.  Breaking things is just breaking things, that's software (it's the same for libraries).  These aren't arbitrary rules that I or anyone else invented for fun, they are that way because doing these things objectively breaks stuff.

As to the rest, yes, you can argue that bypass is more "natural".  Obviously, others would argue the opposite.  This is not a useful argument to have (even if I was interested in engaging with _that_ tone, which I am not _at all_).

> Moreover, definition of lv2:enabled goes into counterpart with lv2:minimum, lv2:maximum and pp:hasStrictBounds properties:

... what?

**Comment by sadko4u** [comment]
You are of course free to break your plugins if you want.

> Well, think about it for a second.  How could you do this? 

If there were **lv2:disabled** or **lv2:bypass** also defined, there would be no problem at all. I culd just tag the corresponding port with this designation.

> How about making the bypass port do nothing, hiding it in UIs, and adding the enabled port? 

Such behaviour spawns yet another RAKES.

> but you've broken that regardless.

Of course, I don't want to spawn RAKES everywhere.

> The rules are there to prevent breaking user's sessions. 

Could tagging port designation with **lv2:bypass** or **lv2:disabled** break user sessions? I suppose **NO**.

> Breaking things is just breaking things, that's software (it's the same for libraries).

Sometimes we need to think about backward compatibility. Implementing **lv2:enable** feature you haven't ever looked into backward compatibility of other plugins if they want to support this feature.

> As to the rest, yes, you can argue that bypass is more "natural".  Obviously, others would argue the opposite.  This is not a useful argument to have (even if I was interested in engaging with _that_ tone, which I am not _at all_).

That's why both should be implemented if we go the way of less resistance.

> ... what?

You've strictly defined the values of tagged port a 'zero', 'greater than zero' and 'less than zero'.
To be conforming with **lv2:minvalue**, **lv2:maxvalue** and **pp:hasStrictBounds**, these values should be defined in such manner:
```
If this value is **greater than the middle of the range**, the plugin processes normally.
If this value is **less or equal than the middle of the range**, the plugin is expected to bypass all
signals unmodified. The plugin must provide a click-free transition between the enabled
and disabled (bypassed) states.

Additionally, values **not in range** are reserved for future use (such as click-free
insertion/removal of latent plugins), and should be treated like **bypassed** by current 
implementations.

!!! By default, minimum value for the range is defined as **0**, the maximum value for the
range is defined as **1** but can be overridden by  **lv2:minvalue** and **lv2:maxvalue**.
The meaning of bypass states should be reverted if **lv2:minvalue** is greater than **lv2:maxvalue**.

```

**Comment by x42** [comment]
> Moreover, definition of lv2:enabled goes into counterpart with lv2:minimum, lv2:maximum and
> pp:hasStrictBounds properties

I fail to see the problem.

[lv2:toggled](http://lv2plug.in/ns/lv2core/lv2core.html#toggled) likewise specifies > 0 meaning true, without constraining a port's effective range.

If you really want to shoot yourself in the foot, you can also set max < min, in a plugin's description without breaking the spec per se ;)

**Comment by drobilla** [comment]
> If there were lv2:disabled or lv2:bypass also defined, there would be no problem at all. I culd just tag the corresponding port with this designation.

As you say, LV2 is very complex.  Adding more complexity - and worse, totally redundant complexity - definitely does not help that situation.

That said, sure, you could have proposed such a thing first, or simply not made this change at all (designations are not a big deal anyway), or worked around it, or... but here we are.

> Sometimes we need to think about backward compatibility. Implementing lv2:enabled feature you haven't ever looked into backward compatibility of other plugins if they want to support this feature.

Let's be honest here: it just doesn't use specifically what _you_ did.  That's annoying, fair enough, but... so it goes.  The proposal was not mine, by the way.

Anyway, nobody said you had to change the port.  Sorry, but you don't get to criticize LV2 for not thinking about backwards compatibility in a thread about you not only breaking it, but "officially" declaring that you don't care about the rules that exist specifically for it.

> That's why both should be implemented if we go the way of less resistance.

Less resistance in this specific case that already happened?  Maybe, but at a global cost.

Part of the "fun" of plugin specs is the diplomacy.  Of course you just want all the things to work exactly the way your plugins already do them, and want all host authors to implement it, regardless of how many complex redundant things they need to implement.  Host authors, of course, want the opposite.

> To be conforming with lv2:minvalue, lv2:maxvalue and pp:hasStrictBounds

It's not "unconforming" with these.  The designation specifically defines these exact values to have exact meanings, yes.  This is intentionally compatible with how toggles are done in LV2.

Regardless, I don't understand why you would change something in a plugin to fit a designation that you clearly disagree with in several ways, then complain about it later.  This is not useful.

**Comment by x42** [comment]
IRC -- Log  Thu Apr 28 09:26:18 2016  (highlight is mine)

> 10:36 rgareus: small detail that "Bypass" switch.  I have a hard time telling what it does.
> 10:36 rgareus: or does green light mean "running not bypassed" ?
> 10:36 rgareus: ie "enabled"
> 10:37 SadKo: It's a 'hot bypass'. And it's active when the light is on.
> 10:38 SadKo: That means that plugin does not affect any changes on the input data.
> 10:38 rgareus: maybe a red LED  is more appropriate. "warning signal is bypassed"
> 10:39 rgareus: or making it clearer: Change it to "enable plugin"  green light: we're running. **That also follows the LV2 spec**.
> 10:40 SadKo: Maybe. I took the design principles from this device: https://global.focusrite.com/sites/default/files/styles/cta_scale_1280/public/liquid_saffire_56222.jpg
> 10:42 rgareus: that has a "Power" green-light = on
> 10:43 SadKo: Yes.
> 10:43 rgareus: green light means it's doing something. in your case green-light: nothing happens (bypassed)
> 10:44 SadKo: Or it can be interpreted as 'Switch is turned on'.

The result of this conversation was LSP plugins changing the color of the LED from green to red.
Well, I tried, and failed to convince.

**Comment by drobilla** [comment]
... do I understand correctly that this is all because of a design decision in a custom UI?!

**Comment by sadko4u** [comment]
@x42 
Plugins have change LED color from green to black according to your recommendations. Please take a look at recent screenshots.

> Change it to "enable plugin" green light: we're running. That also follows the LV2 spec.

Yes it probably could be a much less problems. But if LSP Plugins already were a part of **pulseeffects**, we would step into the same problem.

> do I understand correctly that this is all because of a design decision in a custom UI?!

And this also.

**Comment by sadko4u** [comment]
Simple look into LV2 tree for **bypass** word:
```
grep -R '"bypass"' /usr/local/lib/lv2 | wc -l
66
```

And for **enable** word:
```
egrep -R '"enable[d]?"' /usr/local/lib/lv2 | grep -v "lsp-plugins"
/usr/local/lib/lv2/tamgamp.lv2/tamgamp.ttl:             lv2:symbol "enable" ;
/usr/local/lib/lv2/tamgamp.lv2/tamgamp_gx.ttl:          lv2:symbol "enable" ;
```

Yes, it's not representable since I don't have many plugins installed but there are many plugins which have **bypass** parameter as a functional bypass switch.

In examples there's nothing about 'hot bypass':
https://lv2plug.in/book/

**Comment by x42** [comment]
The decision was not made on popularity, but for technical merit. IIRC the to main points were:

* "bypass" is a double negative: You "enabled" it to "disable" something. That's really bad practice
* enable "bypass" cannot easily be expanded to offer semantics for click-free insertion.  lv2:enable can.

This was discussed at length at the LAC 2015 in Mainz with various plugin devs in attendance.

Anyway, it's too late now to change the spec. -- and you also seem to lack a lot of plugins. most if not all of those running on the MOD have click-free bypass. It was the MOD-devs who started getting the ball rolling on lv2:enable in the first place.

**Comment by sadko4u** [comment]
I can make the only conclusion about LSP Plugins:
- LV2 plugins now have "bypass" replaced by "enabled" port. LADSPA once still have 'bypass' port. VST still has 'bypass' port which is additionally delivered by 'effSetBypass' callback;
- LV2 plugins won't follow the requirement abount URID change since I personally don't consider it as a major change. Almost all normal hosts that support LV2 plugins handle this situation normally.
- The breakage could be avoided if LV2 standard provided more flexible migration way. Sadly but I couldn't participate the discussion in 2015s since I've just stared development at the end of 2015. According to my understanding, the decision made is **wrong** but I can not affect it.

**Comment by drobilla** [comment]
> The breakage could be avoided if LV2 standard provided more flexible migration way

The breakage could have been avoided if you just _didn't break it_!  If you don't care and want to break plugins and not change their URIs, that's fine, but good grief, own your own actions.  LSP is what broke, and (far from encouraging it...) LV2 explicitly forbids this kind of breakage.  Stop blaming LV2 for what you broke.

> Almost all normal hosts that support LV2 plugins handle this situation normally.

A session that contained a bypassed plugin would no longer be bypassed.  Saved state, or automation, and so on, for bypass, would be lost.  Things could both sound different and have dramatically different performance characteristics, including no longer being able to run at all.  You are free to not care, but it is impossible for hosts to handle this situation properly, particularly since the previous port had no designation at all.  That's why we have compatibility rules.  Any serious packaging of LV2 plugins should explicitly test for and reject this kind of thing, because it means that users can't trust that their saved work will keep working.  That's up to packagers though, since there is no centralized repository of LV2 plugins.

**Comment by sadko4u** [comment]
> Stop blaming LV2 for what you broke.
The reason I've broke the compatibility is that I had no other way for keeping plugin URIDs. lv2:enabled feature is very dull, very restricted and inflexible. So to conform to one requirement of LV2 standard I had to break another. The 'only proper' solution you've offered (to hide one bypass and implement another) is ugly. So ugly that I never will follow it.

Now, let's consider I've changed URIDs and I run upgraded bundle of plugins.

> A session that contained a bypassed plugin would no longer be bypassed.

A session that contained a bypassed plugin now won't load due to missing plugin or will replace plugin with empty stubs.

> Saved state, or automation, and so on, for bypass, would be lost.

The same here since plugins changed their URIDs.

> Things could both sound different and have dramatically different performance characteristics, including no longer being able to run at all.

Right. Nothing will be running at all. Since all plugins have changed URIDs and been replaced by empty stubs.

> You are free to not care

I'm caring. And I'm very worried about the future of LV2 standard and it's changes which are controlled by the only one person who decides how they finally should look like.

**Comment by drobilla** [comment]
> The reason I've broke the compatibility is that I had no other way for keeping plugin URIDs.

Objectively false.

> So to conform to one requirement of LV2 standard

lv2:enabled is not a requirement.

> So ugly that I never will follow it.

... and yet, for some reason, you broke a plugin to use lv2:enabled, which is "very dull, very restricted and inflexible", and just a designation that plugins can use to describe a particular kind of port if they want to.

> And I'm very worried about the future of LV2 standard and it's changes which are controlled by the only one person who decides how they finally should look like.

Okay then:

> This was discussed at length at the LAC 2015 in Mainz with various plugin devs in attendance.

Notice how a bunch of people working out a definition of something together was productive?

Try that next time.

**Comment by sadko4u** [comment]
> Try that next time.

The change is *bad* since it tries to put triple logic into a binary parameter and breaks the single responsibility principle, e.g. 'bypass' should be a bypass, and function of insterting of plugin into the chain should be a function of insterting of plugin into a chain. Hmmm, what will you do if you will be required to smoothly remove plugin from the chain?

> This was discussed at length at the LAC 2015 in Mainz with various plugin devs in attendance.

It doesn't matter who participated the discussion. It only matters who merged the final changes into LV2 repository.

**Comment by drobilla** [comment]
> The change is bad

Then why did you make it?

**Comment by sadko4u** [comment]
> > The change is bad
> 
> Then why did you make it?

I've made changes in LSP tree because I received a requirement to synchronize bypass with Ardour's plugin activation button.

And why did you merge such bad solution into LV2 tree?

**Comment by x42** [comment]
> It doesn't matter who participated the discussion. It only matters who merged the final changes into LV2 repository.

Please, leave personal things aside, This is about specs.
I suppose we could have collected sign-off messages, but eventually someone needs to do the final commit and I don't see how it matter who that person is.

> And why did you merge such bad solution into LV2 tree?

I'm still unclear why you think it's a bad solution.

lv2:enabled is the best solution to this issue that I've yet seen for any plugin standard to date.

It defines a tri-state providing for click-free insertion.  It provides optional meta-data for an automatable port. All potential states are defined, without adding any additional or orthogonal constrains that may have effect on other parts of the standard  present or future.

An alternative was to use properties and LV2 Atom messages, but that adds significant overhead for simple plugins.  All that was required was meta-data and semantics for an on/off switch.

PS. Eventually it may benefit from feedback, so that a plugin can inform a host if the bypass/enable transition has been completed. This was discussed, but deemed to to not be significant to make it into the spec at the given time. It's no matter since LV2 is extensible.

**Comment by sadko4u** [comment]
Okay, I have had some time to cool down. Let's be more constructive.

> I'm still unclear why you think it's a bad solution.

As I've described previously, lv2:bypass tries to mix two different functions: a function of bypassing of plugin and a function of inserting of plugin into chain. Moreover, in official specification there is no description about how does the inserting work, how host and plugin should handle it. If there are already devices that use this function, then this breaks a standard since nobody else knows how should deal with it. And again, triple logic of 'bypass' switch looks like if I answered to some question which requires just 'yes/no' with answer 'yes no maybe'.

Additionally, the second argument about that these both functions are separate, is that bypass can be automated but insertion of plugin into chain... Hmm, I suppose it can not be automated since it's a chain modification operation while triggering bypass is just a toggle switch in the chain.

> LV2 Atom messages

Yu're right here. It would be overdesigned to use atoms. But depending on the use case (rememeber, nobody who just read LV2 spec knows how does this function should work?)
the problem could be solved by adding an extension interface.

**Comment by x42** [comment]
> As I've described previously, lv2:bypass tries to mix two different functions: a function of bypassing of plugin and a function of inserting of plugin into chain. 

Yeah, that's awesome, and as it should be: You insert a plugin bypassed and then enable it.

It's like real-world patching: you never wire an enabled component into a system. also guitar pedals all start out as bypassed when you insert the jack...
