### ISSUE TITLE
Build failed for x86_32

### ISSUE THREAD

**Issue by Vascom** [sadko4u/lsp-plugins#89]
I have fail build for x32 system
```
In file included from /builddir/build/BUILD/lsp-plugins-src-1.1.15/include/dsp/dsp.h:11,
                 from sse.cpp:8:
/builddir/build/BUILD/lsp-plugins-src-1.1.15/include/dsp/arch/x86/sse/filters/dynamic.h: In function 'void sse::dyn_biquad_process_x4(float*, const float*, float*, size_t, const biquad_x4_t*)':
/builddir/build/BUILD/lsp-plugins-src-1.1.15/include/common/types.h:81:37: error: 'asm' operand has impossible constraints
   81 |     #define ARCH_X86_ASM(...)       __asm__ __volatile__ ( __VA_ARGS__ )
      |                                     ^~~~~~~
/builddir/build/BUILD/lsp-plugins-src-1.1.15/include/dsp/arch/x86/sse/filters/dynamic.h:171:9: note: in expansion of macro 'ARCH_X86_ASM'
  171 |         ARCH_X86_ASM
      |         ^~~~~~~~~~~~
```
It may be GCC 10 bug but may be not. Check it please.

Full build log https://kojipkgs.fedoraproject.org//work/tasks/3366/42843366/build.log

**Comment by sadko4u** [comment]
Seems that this option:
```-mstackrealign```
has broken the build.

The cause is that function sse::dyn_biquad_process_x4 tries to utilize as most as possible generic-purpose registers to operate on filter data:
https://github.com/sadko4u/lsp-plugins/blob/3f04d804912f6fa7fa978ba8e485d0718c49ffa1/include/dsp/arch/x86/sse/filters/dynamic.h#L327-L334

Here we see that we use five registers to store values hold by **dst**, **src**, **f**, **mask** and **d** variables. Additionally, we use the sixth register to store **count** variable if possible.

So, for 32-bit x86 architecture there will be all free registers taken for use: **eax**, **ebx**, **ecx**, **edx**, **esi** and **edi**. All other GPRs - **ebp** and **esp** are reserved for holding stack frame pointer and stack pointer.

The problem is that **-mstackrealign** requires additional register do do some stack manipulations and reserves it. This denies the **__asm__** directive to allocate the required set of registers.

Possible solutions:
* remove -mstackrealign flag from build
* add -DLSP_PROFILING macro definition which will consider **count** to be a memory-stored value instead of being register-stored value.

**Comment by sadko4u** [comment]
Here's a simple code snippet:

```c++
int f(int a, int b)
{
    float   MASK[4] __attribute__ ((aligned (16)));
    size_t  mask;
    
    __asm__ __volatile__(
        "add %[b], %[a]\n\t"
        : [a] "+r" (a), [mask] "=&r" (mask)
        : [b] "r" (b),
          [MASK] "o" (MASK)
        : "cc", "memory"
    );
    
    return a;
}
```

I've compiled it with:

```bash
g++ -o test.o -c -O2 -m32 -fPIC -mstackrealign test.cpp
```

The result disassembly:
```asm
00000000 <_Z1fii>:
// Generate stack frame
   0:   8d 4c 24 04             lea    0x4(%esp),%ecx
   4:   83 e4 f0                and    $0xfffffff0,%esp
   7:   ff 71 fc                pushl  -0x4(%ecx)
   a:   55                      push   %ebp
   b:   89 e5                   mov    %esp,%ebp
   d:   51                      push   %ecx
   e:   83 ec 14                sub    $0x14,%esp
// Load arguments into registers, ECX is used now instead of EBP
  11:   8b 01                   mov    (%ecx),%eax
  13:   8b 51 04                mov    0x4(%ecx),%edx
// Our __asm__ __volatile__
  16:   01 d0                   add    %edx,%eax
// Restore previous stack frame and return
  18:   83 c4 14                add    $0x14,%esp
  1b:   59                      pop    %ecx
  1c:   5d                      pop    %ebp
  1d:   8d 61 fc                lea    -0x4(%ecx),%esp
  20:   c3                      ret 
```

So it seems that in this case GCC reserves ECX for accessing arguments, so ECX is denied for use in __asm__ statement.

**Comment by Vascom** [comment]
mstackrealign is Fedora's system wide https://fedoraproject.org/wiki/Changes/Update_i686_architectural_baseline_to_include_SSE2
So I prefer use -DLSP_PROFILING macro definition.

Issue can be closed.

**Comment by sadko4u** [comment]
Nice.
